### ISSUE TITLE
Multiple output files number estimation for GADGET format

### ISSUE THREAD

**Issue by robmost** [pynbody/genetIC#111]
Hi,

Is there a way of estimating the number of output files "gadget_num_files" so that the resulting files don't get corrupted?
I'm getting the following message
```
One of the output Fortran fields is too large for the file format.
Writing will proceed, but the resulting file may appear corrupt
Try using gadget_num_files <n> to split your output into multiple files or try using a larger number of files <n>.
```
for a hydro zoom simulation with 
```
# Specify the base-level grid. Basegrid 75 Mpc/h, 1024^3
base_grid 75.0 1024
gadget_particle_type 5

# Zoom region #1 37.5 Mpc/h grid enclosing 30 Mpc/h worth of high-res particles, 2048^3
select_cube 30
zoom_grid 2 2048
gadget_particle_type 1
```
and I'm currently using `gadget_num_files 16`. Each file is around 20 Gb. 

I see that the message is coded around the size of a Fortran integer, i.e. 4 bytes. If I understood it correctly, this parameter file creates a zoom region that uses 2048^3 cells in a cube of 37.5 Mpc/h side-length. Still, only the basegrid particles within a cube of 30 Mpc/h side-length in the middle of the 75 Mpc/h box are actually going to be treated as high-resolution particles, with an effective resolution of 4096^3 because of the size ratio between the zoom region and the box. 

What's the number of high-resolution particles in the end? I assume I should use 2048^3 for the memory estimation, thus 4 bytes * 2048^3 ~ 275 Gb per "field". Is this estimation correct? What file size should I aim for to avoid this message in the future?

**Comment by apontzen** [comment]
The gadget format is based around FORTRAN fields which only accept up to 2^32 bytes. Each double is 8 bytes, so if you take the position array that 24 bytes per particle. Thus around 178M particles per file would appear to be the maximum by my calculations…

**Comment by robmost** [comment]
Thanks for the clarification!

>Each double is 8 bytes, so if you take the position array that’s 24 bytes per particle. Thus around 178M particles per file would appear to be the maximum by my calculations…

I see... and those 24 bytes are just for the position array... If we add the velocity, masses, and ID arrays, and if we consider that gas particles might have extra fields such as the internal energy and density, the required memory is even greater than that.

> alternatively you can hack your version of gadget so that it doesn’t complain about these pointless FORTRAN hang-overs, because genetIC writes it out quite happily despite the warning.

I was concerned about the possible corruption of the output, does this mean the message is there for "legacy" purposes, i.e. if we were to run those ICs with GADGET2? If I run them with GADGET3 could I simply ignore the message and stick to a single IC file?

**Comment by apontzen** [comment]
Since there are so many versions of gadget3 floating around, I'm not really sure whether it will work or not... but definitely the only thing that is corrupt are the fortran size fields so if gadget will ingest the ICs without complaint, all is fine!

**Comment by robmost** [comment]
Oh... Understood.

Thanks again for the clarification!
